export const lang_en = {
	welcome : "Welcome !",
	login : "Login",
	register : "Register",
	username : "Username",
	password : "Password",
	password_confirm : "Confirm password",
	logout_prompt : "Confirm logout?",
	yes : "Yes",
	no : "No",
	delete_prompt : "Confirm account deletion?",
	delete_warning : "Warning! This is a definitive action",
	edit_prompt : "Edit account info",
	new_username : "New username",
	new_password : "New password",
	new_password_confirm : "New password confirm",
	edit : "Edit",
	add_friend_prompt : "Enter your friend's username below !",
	add_friend : "Add friend",
	tournament : "Tournament",
	duel : "Duel",
	logout : "Logout",
	delete : "Delete",
	games_played : "Games played:",
	games_won : "Games won:",
	balls_hit : "Balls hit:",
	friends : "Friends: ",
	leaderboard : "Leaderboard",
	name : "Name",
	played : "Played",
	won : "Won",
	play: "Play !",
	friend_list : "Friends",
	friend_list_title : "Friend list",
	match_history : "Match history",
	against : "Against",
	date : "Date",
	won : "Won ?",
	delete_question : "Delete ?",
	start : "Start",
	reset_camera : "Reset camera",
	page_not_found : "Page not found",
	forbidden : "Forbidden",
	forbidden_message : "You can't access this page because you aren't logged in.",
	host : "Host",
	guest : "Guest",
	anonymous : "An anonymous cat",
	home : "Home",
    confirm : "Confirm",
    two_fa_prompt : "Enter your 2FA code",
    two_fa : "6 number code",
    two_fa_error : "Incorrect code, please try again",
    credentials_error : "Invalid username or password, please try again.",
    server_error : "Error communicating with server, please try again later.",
    username_error : "That username is already in use",
    passwords_error : "Passwords don't match",
    auth_error : "Expired access token",
    friend_error : "Impossible to add this friend, is the username correct?",
    file_size_error : "The file is too large (> 2MB)",
    email: "E-mail address",
    phone: "Phone number",
    password_format: "Must contain at least 6 alphanumeric characters",
    phone_format: "Expecting 10 numbers, starting with '0'",
	send_code: "Send code",
    code_sent: "Your code is on the way, please wait before trying again.",
	code_useless: "Your code is on your authentification app",
	round1: "First round",
	round2: "Second round (finals)",
	players: "Players",
	matches: "Matches",
	result: "Results",
    two_fa_choice: "2FA method",
    two_fa_no_choice_error: "Please choose a 2FA method",
    qr_code_prompt: "This is the QR code you need to use in the app of your choice. Warning ! You'll only see it once, make sure to connect properly",
    proceed: "Proceed",
    qr_code_missing: "Unable to retrieve QR code, please try again later"
}

export const lang_fr = {
	welcome : "Bienvenue !",
	login : "Connexion",
	register : "Inscription",
	username : "Nom d'utilisateur",
	password : "Mot de passe",
	password_confirm : "Confirmation du mot de passe",
	logout_prompt : "Confirmer la deconnexion ?",
	yes : "Oui",
	no : "Non",
	delete_prompt : "Confirmer la suppression du compte?",
	delete_warning : "Attention ! Cette action est definitive",
	edit_prompt : "Changer ses informations",
	new_username : "Nouveau nom d'utilisateur",
	new_password : "Nouveau mot de passe",
	new_password_confirm : "Confirmation du nouveau mot de passe",
	edit : "Editer",
	add_friend_prompt : "Renseignez le nom de votre ami !",
	add_friend : "Ajouter un ami",
	tournament : "Tournoi",
	duel : "Duel",
	logout : "Deconnexion",
	delete : "Suppression",
	games_played : "Parties jouees:",
	games_won : "Parties gagnees:",
	balls_hit : "Balles touchees:",
	friends : "Amis: ",
	leaderboard : "Tableau des scores",
	name : "Nom",
	played : "Jouees",
	won : "Gagnees",
	play: "Jouer !",
	friend_list : "Amis",
	friend_list_title : "Liste d'amis",
	match_history : "Historique de parties",
	against : "Contre",
	date : "Date",
	won : "Gagne ?",
	delete_question : "Supprimer ?",
	start : "Commencer",
	reset_camera : "Reinitialiser la camera",
	page_not_found : "Page inconnue",
	forbidden : "Interdit",
	forbidden_message : "Vous ne pouvez pas acceder a cette page car vous n'etes pas connecte.",
	host : "Hote",
	guest : "Invite",
	anonymous : "Un chat anonyme",
	home : "Accueil",
    confirm : "Confirmer",
    two_fa_prompt : "Renseignez votre code de double authentification",
    two_fa : "Code a 6 chiffres",
    two_fa_error : "Code incorrect, veuillez reesayer.",
    credentials_error : "Nom d'utilisateur ou mot de passe incorrect.",
    server_error : "Erreur de communication avec le serveur, veuillez reessayer plus tard",
    username_error : "Nom d'utilisateur deja utilise.",
    passwords_error : "Les mots de passe ne correspondent pas",
    auth_error : "Jeton d'acces expire",
    friend_error : "Impossible d'ajouter cet ami, est-ce le bon nom d'utilisateur ?",
    file_size_error : "Le fichier est trop large (> 2MB)",
    email: "Addresse mail",
    phone: "Numero de telephone",
    password_format: "Doit contenir au moins 6 caracteres alphanumeriques",
    phone_format: "Veuillez renseigner 10 chiffres, commencant par '0'",
	send_code: "Recevoir le code",
    code_sent: "Votre code arrive, merci d'attendre avant de reessayer.",
	code_useless: "Votre code est sur votre application d'authentification",
	round1: "Premier tour",
	round2: "Second tour (finales)",
	players: "Joueurs",
	matches: "Matchs",
	result: "Résultats",
    two_fa_choice: "Methode 2FA",
    two_fa_no_choice_error: "Veuillez selectioner une methode 2FA",
    qr_code_prompt: "Voici le QR code a renseigner dans l'application de votre choix. Attention ! Vous ne le verrez qu'une fois",
    proceed: "Continuer",
    qr_code_missing: "Impossible de recuperer le QR code, merci de reesayer plus tard"
}

export const lang_es = {
	welcome : "¡Bienvenid@!",
	login : "Iniciar sesión",
	register : "Registrarse",
	username : "Nombre de usuario",
	password : "Contraseña",
	password_confirm : "Confirmar contraseña",
	logout_prompt : "¿Confirmar cierre de sesión?",
	yes : "Sí",
	no : "No",
	delete_prompt : "¿Confirmar eliminación de cuenta?",
	delete_warning : "¡Cuidado! Esta es una acción definitiva",
	edit_prompt : "Editar información de la cuenta",
	new_username : "Nuevo nombre de usuario",
	new_password : "Nueva contraseña",
	new_password_confirm : "Confirmar nueva contraseña",
	edit : "Editar",
	add_friend_prompt : "Ingresa el nombre de usuario de su amigo a continuación",
	add_friend : "Agregar amigo",
	tournament : "Torneo",
	duel : "Duelo",
	logout : "Cerrar sesión",
	delete : "Borrar cuenta",
	games_played : "Partidas jugadas:",
	games_won : "Partidas ganadas:",
	balls_hit : "Bolas golpeadas:",
	friends : "Amigos: ",
	leaderboard : "Tabla de clasificación",
	name : "Nombre",
	played : "Jugados",
	won : "Ganados",
	play: "¡Jugar!",
	friend_list : "Amigos",
	friend_list_title : "Lista de amigos",
	match_history : "Historial de partidas",
	against : "Contra",
	date : "Fecha",
	won : "¿Ganado?",
	delete_question : "¿Borrar?",
	start : "Empezar",
	reset_camera : "Restablecer cámara",
	page_not_found : "Página no encontrada",
	forbidden : "Prohibido",
	forbidden_message : "No puede acceder a esta página porque no ha iniciado sesión.",
	host : "Anfitrión",
	guest : "Invitado",
	anonymous : "Un gato anónimo",
	home : "Inicio",
    confirm : "Confirmar",
    two_fa_prompt : "Ingrese su código 2FA",
    two_fa : "Código de 6 números",
    two_fa_error : "Código incorrecto, inténtelo de nuevo.",
    credentials_error : "Nombre de usuario o contraseña incorrectos, inténtelo de nuevo.",
    server_error : "Error de comunicación con el servidor, inténtelo de nuevo más tarde.",
    username_error : "Ese nombre de usuario ya está en uso.",
    passwords_error : "Las contraseñas no coinciden.",
    auth_error : "Token de acceso expirado.",
    friend_error : "No es posible agregar este amigo, ¿es correcto el nombre de usuario?",
    file_size_error : "El archivo es demasiado grande (> 2MB).",
    email: "Dirección de correo electrónico",
    phone: "Número de teléfono",
    password_format: "Debe contener al menos 6 caracteres alfanuméricos.",
    phone_format: "Se esperan 10 números, comenzando con '0'.",
	send_code: "Enviar código",
    code_sent: "Su código está en camino, por favor espere antes de intentar de nuevo.",
	code_useless: "Su código está en su authenticator app.",
	round1: "Primera ronda",
	round2: "Segunda ronda (final)",
	players: "Jugadores",
	matches: "Partidas",
	result: "Resultados",
    two_fa_choice: "Método 2FA",
    two_fa_no_choice_error: "Por favor elige un método 2FA.",
    qr_code_prompt: "Este es el código QR que debe usar en la aplicación de su elección. ¡Cuidado! Solo lo verás una vez, asegúrase de conectarse correctamente.",
    proceed: "Proceder",
    qr_code_missing: "No se puede recuperar el código QR, por favor intente de nuevo más tarde."
}

